### ISSUE TITLE
[REQ] \e\ build

### ISSUE THREAD

**Issue by MarcoRavich** [dark-N00B/android_device_In_1b#1]
Hi there,
thanks for publish the In 1b (64Gb !) device tree: it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) build for it (and, why not, for any other device you maintain) too.

We opened a 3ad @ [\e\ community](https://community.e.foundation/) were we also linked your repo:

https://community.e.foundation/t/micromax-in-1b-64gb-e7533/43470

If you need, here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Hope can "inspire" you.

Thanks in advance.

**Comment by dark-N00B** [comment]
Will definitely look into it. But FYI this is an incomplete device tree for the above-mentioned device.

**Comment by MarcoRavich** [comment]
Thanks for your reply.

Of course more devices have an - even unofficial - \e\ build, more the user base will probably grow (and hopefully more devs/maintainers will join/support the project), so feel free to "port" \e\ on any of the devices you maintain/use.

Last but not least, consider GSI builds too for a distro quick test on unsupported devices:
https://doc.e.foundation/support-topics/install-GSI
https://doc.e.foundation/support-topics/understand-and-use-gsi.html

Hope that helps !

Thanks again for the volunteer work you do.
